routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UserController')
->middleware(['admin']);
Route::resource('customers', 'CustomerController');
// ->middleware(['admin', 'manager']);

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;
use App\Http\Requests\CustomerUpdateRequest;

class CustomerController extends Controller
{


    public function __construct()
    {
        // parent::__construct();

        // $this->middleware('analyst', ['only' => 'index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::orderByDesc('id')->paginate(10);
        return \view('customers.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerCreateRequest $request)
    {
        
        $customer = Customer::create([
            'name' => $request->full_name,
            'contact_number' => $request->contact_number,
            'address' => $request->address,
            'attatchment' => $request->attatchment
        ]);

        if($customer){
            return redirect('customers')->with(['message' => 'success']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return \view('customers.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(CustomerUpdateRequest $request, Customer $customer)
    {
        $customer = Customer::where('id', $customer->id)->update([
            'name' => $request->full_name,
            'address' => $request->address,
            'contact_number' => $request->contact_number,
            'attachment' => $request->attatchment
        ]);


        if($customer){
            return \redirect('customers')->with(['message' => 'Update Success!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer_delete = $customer->destroy();
        if($customer_delete){
            return redirect('customers')->with(['message' => 'Delete success!']);
        }
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-md-12 content-justify-center">
            <div class="card">
                <div class="card-header">
                    Create New Customer
                </div>
                <div class="card-body">
                    @if($errors->any())
                    <ul>
                        @foreach($errors->all() as $error)
                        <li class="text-danger">
                            {{ $error }}
                        </li>
                        @endforeach
                    </ul>
                    @endif
                        <form action="{{ route('customers.store') }}" method="POST">

                                @csrf

                                <label for="">Name</label>
                                <div class="form-control">
                                    <input type="text" name="full_name" id="full_name" class="form-control" placeholder="Ex: Mr. X">
                                </div>
                                <label for="">Mobile Number</label>
                                <div class="form-control">
                                    <input type="number" maxlength="11" name="contact_number" id="contact_number" class="form-control" placeholder="Ex: 01711223344">
                                </div>
                                
                                <label for="">Address</label>
                                <div class="form-control">
                                    <textarea name="address" id="address" cols="30" rows="1"></textarea>
                                </div>
                                
                                <label for="">Photo</label>
                                <div class="form-control">
                                    <input type="file" name="attachment" id="attachment">
                                </div>
                                
                                <input type="submit" value="Save" id="submitBtn">
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-md-12 content-justify-center">
            <div class="card">
                <div class="card-header">
                    Create New Customer
                </div>
                <div class="card-body">
                    @if($errors->any())
                    <ul>
                        @foreach($errors->all() as $error)
                        <li class="text-danger">
                            {{ $error }}
                        </li>
                        @endforeach
                    </ul>
                    @endif
                        <form action="{{ route('customers.update', $customer->id) }}" method="POST">

                                @csrf
                                @method("put")

                                {{-- <input type="hidden" name="id" value="{{ $customer->id }}"> --}}
                                <label for="">Name</label>
                                <div class="form-control">
                                    <input type="text" name="full_name" id="full_name" value="{{ $customer->name }}" class="form-control" placeholder="Ex: Mr. X">
                                </div>
                                <label for="">Mobile Number</label>
                                <div class="form-control">
                                    <input type="number" maxlength="11" name="contact_number" id="contact_number" value="{{ $customer->contact_number }}" class="form-control" placeholder="Ex: 01711223344">
                                </div>
                                
                                <label for="">Address</label>
                                <div class="form-control">
                                    <textarea name="address" id="address" cols="30" rows="1">{{ $customer->address }}</textarea>
                                </div>
                                
                                <label for="">Photo</label>
                                <div class="form-control">
                                    <img src="{{ $customer->attatchment }}" alt="" width="50" height="50">
                                    <input type="file" name="attatchment" id="attatchment">
                                </div>
                                
                                <input type="submit" value="Save" id="submitBtn">
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')

<div class="wrapper">
        <div class="row">
            <div class="col-md-12 content-justify-center">
                <div class="card">
                    <div class="card-header">
                        Customer List
                    </div>
                    <div class="card-body">

                        @if(Session::get('message'))
                        <div class="alert alert-success">
                            {{ Session::get('message')  }}
                        </div>
                        @endif


                        <table class="table table-bordered">
                            <tr>
                                <th>Name</th>
                                <th>Contact Number</th>
                                <th>Edit</th>
                            </tr> 
                            @foreach($customers as $customer)    
                            <tr>
                                <td>{{ $customer->name }}</td>
                                <td>{{ $customer->contact_number }}</td>
                                <td><a href="{{ route('customers.edit', $customer->id) }}">Edit</a></td>
                            </tr>
                            @endforeach
                        </table>

                    </div>
                </div>
            </div>
        </div>
</div>


@endsection